services:
  db:
    image: postgres
    container_name: db
    ports:
      - '5432:5432'
    volumes:
      - ./dbdata:/var/lib/postgresql/db_data
    user: postgres
    env_file:
      - .env

  app:
    build: ./app
    image: django
    container_name: app
    command:
      - /bin/bash
      - -c
      - |
        python3 obms/manage.py waitfordb &&
        python3 obms/manage.py makemigrations &&
        python3 obms/manage.py migrate &&
        (python3 obms/manage.py createsuperuser --noinput || true) &&
        python3 obms/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

