services:
  db:
    image: postgres
    container_name: db
    ports:
      - '5432:5432'
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    user: postgres
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build: ./app
    image: django
    container_name: app
    command: 
      - /bin/bash
      - -c
      - |
        python3 obms/manage.py makemigrations &&
        python3 obms/manage.py migrate &&
        (python3 obms/manage.py createsuperuser --noinput || true) &&
        python3 obms/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
