name: OBMS CI

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  push:
    branches:
      - '**'

  pull_request:
    branches:
      - '**'

jobs:
  Lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create .env
        run: |
          touch .env
          echo POSTGRES_DB=${{ vars.POSTGRES_DB }} >> .env
          echo POSTGRES_NAME=${{ vars.POSTGRES_NAME }} >> .env
          echo POSTGRES_USER=${{ vars.POSTGRES_USER }} >> .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
          echo DJANGO_SUPERUSER_USERNAME=${{ secrets.DJANGO_SUPERUSER_USERNAME }} >> .env
          echo DJANGO_SUPERUSER_EMAIL=${{ secrets.DJANGO_SUPERUSER_EMAIL }} >> .env
          echo DJANGO_SUPERUSER_PASSWORD=${{ secrets.DJANGO_SUPERUSER_PASSWORD }} >> .env
          cat .env



      # - name: Compose OBMS
      #   run: docker compose up --build

      # - name: Setup Python 3.10
      #   uses: actions/setup-python@v3
      #   with:
      #     python-version: 3.10

      # - name: Install Linters
      #   run: pip install djlint pylint pylint_django

      # - name: Lint Python
      #   id: py-lint
      #   run: echo "python_rating=$(pylint ./app/obms)\n" >> $GITHUB_OUTPUT

      # - name: Check Python Linting
      #   if: ${{ !steps.py-lint.outputs.python_rating }}
      #   uses: actions/github-script@v3
      #   with:
      #     script: |
      #         core.setFailed('Linting found errors! Run a pylint on app/obms to see them.')


      # - name: Lint HTML and Jinja Templates
      #   id: dj-lint
      #   run: djlint echo "html_rating=$(./app/obms/librarian/templates --extension=html --lint | grep 'found 0 errors')

      # - name: Check HTML Linting
      #   if: ${{ !steps.dj-lint.outputs.html_rating }}
      #   uses: actions/github-script@v3
      #   with:
      #     script: |
      #         core.setFailed('Linting found errors! Run djlint on the templates directory to see them.')




